### ISSUE TITLE
Opened LogicApp json file isn't auto-updated when changes made in portal

### ISSUE THREAD

**Issue by jongio** [microsoft/vscode-azurelogicapps#48] opened 2018-10-05 21:39 UTC
1. open json file in vs code
2. go to portal and change the logic app
3. come back to vs code

I was expected the json file to auto-update, but I had to click on the edit icon.

**Comment by joechung-msft** [comment] 2018-10-08 22:17
That is by design.  When you click the Edit button, you download a copy of the Logic App definition so you can view it and-or make changes, similar to how the code view works on the portal.

**Comment by jongio** [comment] 2018-10-08 22:31
It would be good to indicate that the file is out of sync with the server.

**Comment by joechung-msft** [comment] 2020-10-03 23:39
Closing all the enhancement requests. v2 is the future of Logic Apps on Visual Studio Code.

**Closed by joechung-msft** 2020-10-03 23:39 UTC
Labels: enhancement
