### ISSUE TITLE
Unable to create project when .NET SDK 5.0 is installed side-by-side

### ISSUE THREAD

**Issue by trevonmckay** [microsoft/vscode-azurelogicapps#176] opened 2020-09-29 14:18 UTC
I have the following .NET SDKs installed

```
PS C:\Users\trevo\source\repos\dgs\logicapps> dotnet --list-sdks
2.1.602 [C:\Program Files\dotnet\sdk]
2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009677 [C:\Program Files\dotnet\sdk]
2.1.800-preview-009696 [C:\Program Files\dotnet\sdk]
2.1.800 [C:\Program Files\dotnet\sdk]
2.2.105 [C:\Program Files\dotnet\sdk]
3.1.101 [C:\Program Files\dotnet\sdk]
3.1.300-preview-015135 [C:\Program Files\dotnet\sdk]
5.0.100-rc.1.20452.10 [C:\Program Files\dotnet\sdk] 
```

When I try to create a Logic Apps (Preview) project from VS Code I get the error

```
Error: You must have the [.NET Core SDK](https://aka.ms/AA4ac70) installed to perform this operation. See [here](https://aka.ms/AA1tpij) for supported versions.
```

I have a global.json file in the same directory but that doesn't seem to help
```
{
  "sdk": {
    "version": "3.1.402",
    "rollForward": "disable"
  }
}
```

**Comment by joechung-msft** [comment] 2020-09-30 04:50
Duplicate of https://github.com/Azure/logicapps/issues/160

**Closed by joechung-msft** 2020-09-30 04:50 UTC
Labels: preview
