### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by prafullkotecha** [microsoft/vscode-azurelogicapps#201] opened 2021-04-01 10:24 UTC
- Issue Type: `Performance`
- Extension Name: `vscode-logicapps`
- Extension Version: `1.0.8`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.55.0-insider`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\prafu\AppData\Local\Temp\ms-azuretools.vscode-logicapps-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by joechung-msft** [comment] 2021-04-01 20:58
Duplicate of #149.

**Closed by joechung-msft** 2021-04-01 20:58 UTC
